import { PrimaryGeneratedColumn } from "typeorm";
import { TimestampedEntity } from "./timestamped.entity";

/**
 * Abstract base entity with a unique identifier.
 * All other entities should extend this class.
 */
export abstract class CommonEntity extends TimestampedEntity {
  /**
   * The unique identifier for an entity.
   * Auto-generated by the database.
   * @type {number}
   */
  @PrimaryGeneratedColumn('increment')
  public id: number;
}